export interface ModelMeta {
  id: string
  name: string
  provider: string
  is_free: boolean
  context_window: number
  description: string
  min_role: 'basic' | 'standard' | 'advanced' | 'admin'
  cost_input_per_1m: number
  cost_output_per_1m: number
  scores: {
    reasoning: number   // 0-100
    coding: number      // 0-100
    writing: number     // 0-100
    speed: number       // 0-100 (mayor = más rápido)
  }
  tags?: string[]
}

export const AVAILABLE_MODELS: ModelMeta[] = [
  // ── FREE ────────────────────────────────────────────────────────────────
  {
    id: 'nvidia/nemotron-nano-9b-v2:free',
    name: 'Nemotron Nano 9B',
    provider: 'NVIDIA',
    is_free: true,
    context_window: 32000,
    description: 'Gratuito. Rápido y ligero, ideal para consultas del día a día.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 52, coding: 48, writing: 55, speed: 95 },
    tags: ['rápido', 'ligero'],
  },
  {
    id: 'google/gemma-4-31b-it:free',
    name: 'Gemma 4 31B',
    provider: 'Google',
    is_free: true,
    context_window: 262144,
    description: 'Gratuito. Muy capaz para redacción y análisis de Google.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 68, coding: 62, writing: 74, speed: 78 },
    tags: ['redacción', 'análisis'],
  },
  {
    id: 'nvidia/nemotron-3-super-120b-a12b:free',
    name: 'Nemotron 120B',
    provider: 'NVIDIA',
    is_free: true,
    context_window: 1000000,
    description: 'Gratuito. Modelo potente de NVIDIA con 1M de contexto.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 76, coding: 72, writing: 74, speed: 55 },
    tags: ['contexto largo', 'potente'],
  },
  {
    id: 'openai/gpt-oss-120b:free',
    name: 'GPT OSS 120B',
    provider: 'OpenAI',
    is_free: true,
    context_window: 131072,
    description: 'Gratuito. Modelo open source de OpenAI para razonamiento y análisis.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 78, coding: 74, writing: 72, speed: 58 },
    tags: ['razonamiento', 'open source'],
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct:free',
    name: 'Llama 3.3 70B',
    provider: 'Meta',
    is_free: true,
    context_window: 131072,
    description: 'Gratuito. Llama 3.3 de Meta, excelente para redacción y análisis general.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 72, coding: 68, writing: 76, speed: 70 },
    tags: ['redacción', 'versátil'],
  },
  {
    id: 'nvidia/nemotron-3-ultra-550b-a55b:free',
    name: 'Nemotron Ultra 550B',
    provider: 'NVIDIA',
    is_free: true,
    context_window: 1000000,
    description: 'Gratuito. El modelo open source más potente disponible, 550B parámetros.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 84, coding: 80, writing: 80, speed: 35 },
    tags: ['potente', 'contexto largo'],
  },
  {
    id: 'qwen/qwen3-coder:free',
    name: 'Qwen3 Coder',
    provider: 'Qwen',
    is_free: true,
    context_window: 1048576,
    description: 'Gratuito. Especializado en código y razonamiento técnico.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 79, coding: 91, writing: 65, speed: 62 },
    tags: ['código', 'técnico'],
  },
  {
    id: 'qwen/qwen3-next-80b-a3b-instruct:free',
    name: 'Qwen3 Next 80B',
    provider: 'Qwen',
    is_free: true,
    context_window: 131072,
    description: 'Gratuito. Último modelo de instrucción de Qwen, muy capaz en análisis y redacción.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 75, coding: 72, writing: 78, speed: 65 },
    tags: ['instrucción', 'análisis'],
  },
  {
    id: 'openai/gpt-oss-20b:free',
    name: 'GPT OSS 20B',
    provider: 'OpenAI',
    is_free: true,
    context_window: 131072,
    description: 'Gratuito. Versión compacta y rápida del modelo open source de OpenAI.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 60, coding: 58, writing: 62, speed: 88 },
    tags: ['rápido', 'ligero'],
  },
  {
    id: 'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free',
    name: 'Nemotron Omni 30B Reasoning',
    provider: 'NVIDIA',
    is_free: true,
    context_window: 131072,
    description: 'Gratuito. Modelo de razonamiento de NVIDIA con capacidad multimodal.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 77, coding: 65, writing: 64, speed: 72 },
    tags: ['razonamiento', 'multimodal'],
  },

  // ── GOOGLE / GEMINI ──────────────────────────────────────────────────────
  {
    id: 'google/gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    is_free: true,
    context_window: 1048576,
    description: 'Gratuito (Workspace). Rápido, 1M de contexto, ideal para consultas frecuentes.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 78, coding: 74, writing: 80, speed: 90 },
    tags: ['rápido', 'contexto largo'],
  },
  {
    id: 'google/gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    is_free: true,
    context_window: 1048576,
    description: 'Gratuito (Workspace). El más capaz de Google, 1M de contexto para documentos largos.',
    min_role: 'basic',
    cost_input_per_1m: 0,
    cost_output_per_1m: 0,
    scores: { reasoning: 88, coding: 84, writing: 87, speed: 68 },
    tags: ['potente', 'contexto largo'],
  },

  // ── OPENAI ────────────────────────────────────────────────────────────────
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    is_free: false,
    context_window: 128000,
    description: 'Versión económica de GPT-4o. Equilibrio perfecto entre calidad y coste.',
    min_role: 'basic',
    cost_input_per_1m: 0.15,
    cost_output_per_1m: 0.60,
    scores: { reasoning: 72, coding: 70, writing: 75, speed: 88 },
    tags: ['económico', 'rápido'],
  },
  {
    id: 'openai/o4-mini',
    name: 'o4-mini',
    provider: 'OpenAI',
    is_free: false,
    context_window: 200000,
    description: 'Modelo de razonamiento compacto de OpenAI. Excelente para análisis lógico y matemático.',
    min_role: 'basic',
    cost_input_per_1m: 1.10,
    cost_output_per_1m: 4.40,
    scores: { reasoning: 88, coding: 85, writing: 72, speed: 75 },
    tags: ['razonamiento', 'matemáticas'],
  },
  {
    id: 'openai/gpt-4.1',
    name: 'GPT-4.1',
    provider: 'OpenAI',
    is_free: false,
    context_window: 1047576,
    description: 'Última versión de GPT-4. 1M de contexto, muy capaz en redacción y análisis.',
    min_role: 'basic',
    cost_input_per_1m: 2.00,
    cost_output_per_1m: 8.00,
    scores: { reasoning: 85, coding: 82, writing: 88, speed: 72 },
    tags: ['redacción', 'contexto largo'],
  },
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    is_free: false,
    context_window: 128000,
    description: 'Modelo avanzado de OpenAI. Muy capaz en multitarea y análisis.',
    min_role: 'basic',
    cost_input_per_1m: 2.50,
    cost_output_per_1m: 10.00,
    scores: { reasoning: 84, coding: 80, writing: 86, speed: 76 },
    tags: ['versátil', 'multimodal'],
  },
  {
    id: 'openai/o3',
    name: 'o3',
    provider: 'OpenAI',
    is_free: false,
    context_window: 200000,
    description: 'Modelo de razonamiento avanzado de OpenAI. Para problemas complejos y estratégicos.',
    min_role: 'basic',
    cost_input_per_1m: 2.00,
    cost_output_per_1m: 8.00,
    scores: { reasoning: 95, coding: 90, writing: 80, speed: 45 },
    tags: ['razonamiento', 'estrategia'],
  },

  // ── ANTHROPIC / CLAUDE ───────────────────────────────────────────────────
  {
    id: 'anthropic/claude-haiku-4.5',
    name: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    is_free: false,
    context_window: 200000,
    description: 'El Claude más rápido y económico. Ideal para tareas rápidas y alto volumen.',
    min_role: 'basic',
    cost_input_per_1m: 1.00,
    cost_output_per_1m: 5.00,
    scores: { reasoning: 74, coding: 72, writing: 78, speed: 92 },
    tags: ['rápido', 'económico'],
  },
  {
    id: 'anthropic/claude-sonnet-4.6',
    name: 'Claude Sonnet 4.6',
    provider: 'Anthropic',
    is_free: false,
    context_window: 1000000,
    description: 'Alto rendimiento. 1M contexto, ideal para propuestas, licitaciones y análisis complejos.',
    min_role: 'basic',
    cost_input_per_1m: 3.00,
    cost_output_per_1m: 15.00,
    scores: { reasoning: 90, coding: 88, writing: 92, speed: 70 },
    tags: ['redacción', 'análisis', 'contexto largo'],
  },
  {
    id: 'anthropic/claude-opus-4.8',
    name: 'Claude Opus 4.8',
    provider: 'Anthropic',
    is_free: false,
    context_window: 1000000,
    description: 'El más potente de Anthropic. 1M contexto, para tareas de máxima complejidad.',
    min_role: 'basic',
    cost_input_per_1m: 5.00,
    cost_output_per_1m: 25.00,
    scores: { reasoning: 96, coding: 92, writing: 95, speed: 50 },
    tags: ['potente', 'complejo'],
  },
]

export function getFreeModels() {
  return AVAILABLE_MODELS.filter(m => m.is_free)
}

export function getModelById(id: string) {
  return AVAILABLE_MODELS.find(m => m.id === id)
}
